<?php
?>
<div class="blog-container" data-bind="scope: 'blog'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "blog": {
                        "component": "Habr_Blog/js/blog",
                        "title": "Hello World",
                        "posts": [
                            {
                            "id": 1,
                            "title": "First Post",
                            "url": "https://ce235habr.docker.loc/blog/first-post",
                            "published_date": "2020-06-14",
                            "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries.",
                            "author": "Pavel"
                            },
                            {
                            "id": 2,
                            "title": "Second Post",
                            "url": "https://ce235habr.docker.loc/blog/second-post",
                            "published_date": "2020-06-13",
                            "content": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries.",
                            "author": "Pavel"
                            }
                        ]
                    }
                }
            }
        }
    }
</script>
