<?php
?>
<div class="blog-container" data-bind="scope: 'blog'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "blog": {
                        "component": "Habr_Blog/js/blog",
                        "title": "Hello World",
                        "posts": [
                            {
                            "id": 1,
                            "title": "First Post",
                            "published_date": "2020-06-14"
                            },
                            {
                            "id": 2,
                            "title": "Decond Post",
                            "published_date": "2020-06-13"
                            }
                        ]
                    }
                }
            }
        }
    }
</script>
